package com.dptosweb.model.ciudades;

// Generated Apr 2, 2014 7:45:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArgDepartamentos generated by hbm2java
 */
@Entity
@Table(name = "arg_departamentos", catalog = "argentina")
public class ArgDepartamentos implements java.io.Serializable {

	private int id;
	private ArgProvincias argProvincias;
	private String nombre;
	private Set argLocalidadeses = new HashSet(0);

	public ArgDepartamentos() {
	}

	public ArgDepartamentos(int id, ArgProvincias argProvincias, String nombre) {
		this.id = id;
		this.argProvincias = argProvincias;
		this.nombre = nombre;
	}

	public ArgDepartamentos(int id, ArgProvincias argProvincias, String nombre,
			Set argLocalidadeses) {
		this.id = id;
		this.argProvincias = argProvincias;
		this.nombre = nombre;
		this.argLocalidadeses = argLocalidadeses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_provincia", nullable = false)
	public ArgProvincias getArgProvincias() {
		return this.argProvincias;
	}

	public void setArgProvincias(ArgProvincias argProvincias) {
		this.argProvincias = argProvincias;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "argDepartamentos")
	public Set getArgLocalidadeses() {
		return this.argLocalidadeses;
	}

	public void setArgLocalidadeses(Set argLocalidadeses) {
		this.argLocalidadeses = argLocalidadeses;
	}

}
