package com.dptosweb.model.ciudades;

// Generated Apr 2, 2014 7:45:04 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArgLocalidades generated by hbm2java
 */
@Entity
@Table(name = "arg_localidades", catalog = "argentina")
public class ArgLocalidades implements java.io.Serializable {

	private int id;
	private ArgDepartamentos argDepartamentos;
	private ArgProvincias argProvincias;
	private String nombre;

	public ArgLocalidades() {
	}

	public ArgLocalidades(int id, ArgDepartamentos argDepartamentos,
			ArgProvincias argProvincias, String nombre) {
		this.id = id;
		this.argDepartamentos = argDepartamentos;
		this.argProvincias = argProvincias;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento", nullable = false)
	public ArgDepartamentos getArgDepartamentos() {
		return this.argDepartamentos;
	}

	public void setArgDepartamentos(ArgDepartamentos argDepartamentos) {
		this.argDepartamentos = argDepartamentos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_provincia", nullable = false)
	public ArgProvincias getArgProvincias() {
		return this.argProvincias;
	}

	public void setArgProvincias(ArgProvincias argProvincias) {
		this.argProvincias = argProvincias;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
