package com.dptosweb.model.ciudades;

// Generated Apr 2, 2014 7:45:04 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ArgProvincias generated by hbm2java
 */
@Entity
@Table(name = "arg_provincias", catalog = "argentina")
public class ArgProvincias implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set argDepartamentoses = new HashSet(0);
	private Set argLocalidadeses = new HashSet(0);

	public ArgProvincias() {
	}

	public ArgProvincias(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	public ArgProvincias(int id, String nombre, Set argDepartamentoses,
			Set argLocalidadeses) {
		this.id = id;
		this.nombre = nombre;
		this.argDepartamentoses = argDepartamentoses;
		this.argLocalidadeses = argLocalidadeses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "argProvincias")
	public Set getArgDepartamentoses() {
		return this.argDepartamentoses;
	}

	public void setArgDepartamentoses(Set argDepartamentoses) {
		this.argDepartamentoses = argDepartamentoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "argProvincias")
	public Set getArgLocalidadeses() {
		return this.argLocalidadeses;
	}

	public void setArgLocalidadeses(Set argLocalidadeses) {
		this.argLocalidadeses = argLocalidadeses;
	}

}
